// This file is autogenerated. Changes will be overwritten.
#include "3PL2EUVYPL/moc_BleServer.cpp"
#include "LUN34XP4RL/moc_LedController.cpp"
#include "LUN34XP4RL/moc_MotorController.cpp"
#include "LUN34XP4RL/moc_SpeedSensor.cpp"
#include "LUN34XP4RL/moc_TempSensor.cpp"
#include "IVK4DJNV27/moc_VehicleModel.cpp"
